#
# Mailhub Backend
#

openapi: '3.0.3'

info:
  description: Mailhub Backend
  version: 0.1.0
  title: Mailhub Backend

servers:
  - url: http://localhost:3010/v0

paths:
  /login:
    post:
      description: Login
      requestBody:
        description: Request Body
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Credentials'
      responses:
        200:
          description: Email Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnexpectedError'
  /register:
    post:
      description: Register
      requestBody:
        description: Request Body
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Register'
      responses:
        201:
          description: Books Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterSuccess'
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnexpectedError'

  /logout:
    post:
      description: Logout
      responses:
        200:
          description: Logout User Response
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnexpectedError'

  /email:
    get:
      security:
        - bearerAuth: []

      parameters:
        - in: query
          name: mailbox
          required: false
          description: Get all emails in a specific mailbox
          schema:
            $ref: '#/components/schemas/EmailArray'
      responses:
        200:
          description: GET EMAIL
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmailArray'
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnexpectedError'
    post:
      security:
        - bearerAuth: []
      requestBody:
        description: Request Body
        required: true
        content: 
          application/json:
            schema:
              $ref: '#/components/schemas/EmailRequest'
      responses:
        200:
          description:  Return Email posted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmailArray'
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnexpectedError'
  
  /email/{id}:      
    get:
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id 
          required: true
          description: Get mail by ID of user
          schema:
            type: string

      responses:
        200:
          description: Email With Content Property
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmailArr'
        404:
          description: Not Found 

    put:
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id 
          required: true
          description: Get mail by ID of user
          schema:
            type: string

      responses:
        200:
          description: Email With Content Property
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmailArr'
        404:
          description: Not Found 

      

      
components:
  schemas:
    UnexpectedError:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string

    Credentials:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
      required:
        - email
        - password

    Register:
      type: object
      properties:
        name:
          type: object
          properties:
            first:
              type: string
            last:
              type: string
        email:
          type: string
          format: email
        password:
          type: string
      required:
        - name
        - email
        - password

    RegisterSuccess:
      type: string
      properties:
        firstname:
          type: string

    User:
      type: object
      properties:
        email:
          type: string
          format: email
        accessToken:
          type: string
      required:
        - email
        - accessToken

    EmailArray:
      type: array
      properties:
        items:
          $ref: '#/components/schemas/EmailRes'

    EmailArr:
      type: array
      properties:
        items:
          $ref: '#/components/schemas/EmailSingle'

    EmailRes:
      type: object
      properties:
        SenderEmail:
          type: string
          format: email
        ReceiverEmail:
          type: string
          format: email
        subject:
          type: string
        body:
          type: string
        sent_time:
          type: string
          format: date-time
      required:
        - SenderEmail
        - ReceiverEmail
        - subject
        - body
        - sent_time

    EmailSingle:
      type: object
      properties:
        mailid:
          type: string
        mail:
          type: object
          properties:
            to:
              type: string
              format: email
            from:
              type: string
              format: email
            subject:
              type: string
            content:
              type: string
            sent:
              type: string
              format: date-time
      required:
        - mailid
        - mail

    EmailRequest:
      type: object
      properties:
        ReceiverEmail:
          type: string
          format: email
        subject:
          type: string
        body:
          type: string
      required:
        - ReceiverEmail
        - subject
        - body

  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes